#!/bin/sh

# Check if we actually have commits to push
commits=`git log @{u}..`
if [ -z "$commits" ]; then
    exit 0
fi

# Site to upload
LIVE_FOLDER="host@site.com:/folder/path"
#Password server
PASSWORD="password"

# List files to up
DEPLOY_FILES="$(pwd)/.git/deploy-files" 
#Prevent up list of this files
EXCLUDE_LIST="$(pwd)/.git/exclude-files"

# Get branch name from ref head
CURRENT_BRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')



# just in master or can you change to new branch "deploy"
if [ "master" == "$CURRENT_BRANCH" ]; then
	echo "*******************PUSH-TO-DEPLOY********************"
	
    #Get file list modify or new and save in {$DEPLOY_FILES}
	git diff --diff-filter=d --stat --cached --name-only origin/master > $DEPLOY_FILES

	sshpass -p "$PASSWORD" rsync  -avz --exclude-from $EXCLUDE_LIST --files-from=$DEPLOY_FILES  "$(pwd)" $LIVE_FOLDER
fi

exit 0;
